[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4.41", features = ["serde"] }
common = { path = "../Common" }
dashmap = "6.1.0"
deadpool-postgres = "0.14.1"
futures = "0.3.31"
futures-util = "0.3.31"
http = "1.3.1"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
polars = { version = "0.48.1", features = ["parquet", "timezones"] }
rand = "0.9.2"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
server = { path = "../Server" }
tokio = { version = "1.47.0" , features = ["full"] }
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }
tokio-tungstenite = "0.24.0"
url = "2.5.4"
